{% set name = "jupyterlab-git" %}
{% set version = "0.51.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.replace('-','_')}}/{{ name.replace('-','_')}}-{{ version }}.tar.gz
  sha256: c3bd9405dbdb69cf2fe56fb05474f2d7217d45d177f38fec92b45ff890cbc146

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version >=0.3.2
    - pip
    - python
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
  run:
    - jupyter_server >=2.0.1,<3
    - python
    - nbdime >=4.0.1,<4.1.0
    - nbformat
    - packaging
    - pexpect
    - traitlets >=5.0,<6.0
  run_constrained:
    - jupyterlab >=4.0.0,<5

test:
  requires:
    - jupyterlab >=4.0.0,<5
    - pip
    - m2-grep  # [win]
  imports:
    - jupyterlab_git
  commands:
    - pip check
    - jupyter server extension list
    - jupyter server extension list 2>&1 | grep -ie "jupyterlab_git.*OK"
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "@jupyterlab/git.*OK.*(python, jupyterlab-git)"

about:
  home: https://github.com/jupyterlab/jupyterlab-git
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Git extension for JupyterLab
  description: A JupyterLab extension for version control using git
  dev_url: https://github.com/jupyterlab/jupyterlab-git
  doc_url: https://github.com/jupyterlab/jupyterlab-git

extra:
  recipe-maintainers:
    - dbast
    - blink1073
    - fcollonval
