{% set name = "jupyterlab-git" %}
{% set version = "0.7.1" %}
{% set sha256 = "11db01b33b8de2cb14a18e15e0575fa9f727393921b60f85420c7803bc6c17ea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyterlab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python

requirements:
  build:
    - nodejs
  host:
    - jupyterlab >0.35.0,<1.0.0
    - pip
    - psutil
    - python >=3.5
  run:
    - jupyterlab >0.35.0,<1.0.0
    - nodejs
    - psutil
    - python >=3.5

test:
  imports:
    - jupyterlab_git
  commands:
    - jupyter labextension list
    - jupyter lab build

about:
  home: https://github.com/jupyterlab/jupyterlab-git
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Git extension for JupyterLab
  description: A JupyterLab extension for version control using git
  dev_url: https://github.com/jupyterlab/jupyterlab-git

extra:
  recipe-maintainers:
    - dbast
    - blink1073
