{% set name = "jupyterlab-git" %}
{% set version = "0.23.3" %}
{% set sha256 = "20a4954d8d1b1eb6f9111cd15d6a598bd7ff72b08797cf5e86c5a55827c85a1d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_git/jupyterlab_git-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - jupyterlab >=2.0.0,<3.0.0
    - python >=3.6,<4.0
    - nbdime >=2.0.0,<3.0.0
    - nodejs
    - packaging
    - pexpect

test:
  requires:
    - pip
  imports:
    - jupyterlab_git
  commands:
    - pip check
    - jupyter labextension list
    - jupyter lab build

about:
  home: https://github.com/jupyterlab/jupyterlab-git
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Git extension for JupyterLab
  description: A JupyterLab extension for version control using git
  dev_url: https://github.com/jupyterlab/jupyterlab-git

extra:
  recipe-maintainers:
    - dbast
    - blink1073
    - fcollonval
