{% set name = "jupyterlab-git" %}
{% set version = "0.30.1" %}
{% set sha256 = "f44a33cf59b424e0b5ff984b18eae33e45dab1ef9dc1901b1dd23f9adff15df2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_git/jupyterlab_git-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --install-option="--skip-npm" -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - jupyterlab =3
    - jupyter-packaging =0.7
  run:
    - jupyterlab =3
    - python >=3.6,<4.0
    - nbdime =3
    - nbformat
    - packaging
    - pexpect

test:
  requires:
    - pip
  imports:
    - jupyterlab_git
  commands:
    - pip check
    - jupyter server extension list
    - jupyter server extension list 2>&1 | grep -ie "jupyterlab_git.*OK"
    - jupyter labextension list
    - jupyter labextension list 2>&1 | grep -ie "@jupyterlab/git.*OK.*(python, jupyterlab-git)"

about:
  home: https://github.com/jupyterlab/jupyterlab-git
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Git extension for JupyterLab
  description: A JupyterLab extension for version control using git
  dev_url: https://github.com/jupyterlab/jupyterlab-git

extra:
  recipe-maintainers:
    - dbast
    - blink1073
    - fcollonval
