{% set name = "jupyterlab-git" %}
{% set version = "0.8" %}
{% set sha256 = "17b3c57c5ed1369deb5b7a63edb9b9b2caa762f7ea951df061346bfc1857e5be" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyterlab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python

requirements:
  build:
    - nodejs
  host:
    - jupyterlab >=1.0.0
    - pip
    - python >=3.5
  run:
    - jupyterlab >=1.0.0
    - nodejs
    - python >=3.5
    - nbdime >=1.1.0

test:
  imports:
    - jupyterlab_git
  commands:
    - jupyter labextension list
    - jupyter lab build

about:
  home: https://github.com/jupyterlab/jupyterlab-git
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Git extension for JupyterLab
  description: A JupyterLab extension for version control using git
  dev_url: https://github.com/jupyterlab/jupyterlab-git

extra:
  recipe-maintainers:
    - dbast
    - blink1073
