{% set name = "jupyterlab-git" %}
{% set version = "0.21.0" %}
{% set sha256 = "72dba635acf13012d6e7b0c9fba9ad8907b0d7c9e31be91d0045f70616313b63" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_git/jupyterlab_git-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - jupyterlab >=2.0.0
    - python >=3.5
    - nbdime >=2.0.0
    - nodejs
    - pexpect

test:
  imports:
    - jupyterlab_git
  commands:
    - jupyter labextension list
    - jupyter lab build

about:
  home: https://github.com/jupyterlab/jupyterlab-git
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Git extension for JupyterLab
  description: A JupyterLab extension for version control using git
  dev_url: https://github.com/jupyterlab/jupyterlab-git

extra:
  recipe-maintainers:
    - dbast
    - blink1073
    - fcollonval
