travis:
  secure:
    BINSTAR_TOKEN: A3/7JgmQ2q/QNa1n6a0TVSe6HdxjDTFZCaG+KySVClahZQPOif8XOyaKo+e43gG5hv4u8xwlNK7VU58IQga/LSG7X5WiTsZrnV9q+JrJ7C8sQfkbIL+Nr4UYzqjCPEaw5rQw06I8gqe3DpNGTzXqY9ZQChu4WZx5RAnxsjBJxEee4aHUYm1ZKUgcqXMXQOfqIQZ1d8544ow64jZM2MRqaQl9WxymM5/qb7CGffHSA8yvFhePJsewpHk6XdkVMMscUFgzv8jxVIDq2jDgBVNZINXQf/bJ9hpA7o+sefK0IpWkfFwxhSGUQf6ZClMRUb+Qv3NdorWAbVSUkN0+CdusWk3MSAVXHPtZx4qjsi1tAbgX7RtsVA/chsWKAYyx3q7CFaePK498svnqbF54X8wuxmnaySP5Si02JD/sYTK9WjA5+02/UsJfeJaQfSKWpTgDDhGxGmRnFQWUHh8/Uv6GGIU7XFOJJYX9pM1u7vlwTIxXuG8x2m6jm86uuCInjBHVBwg8HMXXPA6myev9jUE0eoiK5LFt7jLDq1FY9Qz8xlMH0S1Kjdi7uP0QkFcEgoPrelqOs5pPsd8cHt55gFPaOpRLnE5H7nIacWG3fM5ijc/XJP4SOPIODmRelS7tbT19GYCHg5S1HfkV58m2cDS2JhShCUqRwk3LTOnlvF0AIxc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
